//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
[System.Xml.Serialization.XmlRootAttribute("ORF", Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd", IsNullable=false)]
public partial class TORF {
    
    private TProjekt projektField;
    
    private TRozpocet rozpocetField;
    
    private TDefinice definiceField;
    
    private TVerze verzeField;
    
    /// <remarks/>
    public TProjekt Projekt {
        get {
            return this.projektField;
        }
        set {
            this.projektField = value;
        }
    }
    
    /// <remarks/>
    public TRozpocet Rozpocet {
        get {
            return this.rozpocetField;
        }
        set {
            this.rozpocetField = value;
        }
    }
    
    /// <remarks/>
    public TDefinice Definice {
        get {
            return this.definiceField;
        }
        set {
            this.definiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TVerze Verze {
        get {
            return this.verzeField;
        }
        set {
            this.verzeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TProjekt : TIdentita {
    
    private string adresaField;
    
    private TPoloha umisteniField;
    
    private string evidencniCisloField;
    
    private System.DateTime datumZahajeniRealizaceField;
    
    private bool datumZahajeniRealizaceFieldSpecified;
    
    private System.DateTime datumUkonceniRealizaceField;
    
    private bool datumUkonceniRealizaceFieldSpecified;
    
    private TMena menaField;
    
    /// <remarks/>
    public string Adresa {
        get {
            return this.adresaField;
        }
        set {
            this.adresaField = value;
        }
    }
    
    /// <remarks/>
    public TPoloha Umisteni {
        get {
            return this.umisteniField;
        }
        set {
            this.umisteniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EvidencniCislo {
        get {
            return this.evidencniCisloField;
        }
        set {
            this.evidencniCisloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime DatumZahajeniRealizace {
        get {
            return this.datumZahajeniRealizaceField;
        }
        set {
            this.datumZahajeniRealizaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DatumZahajeniRealizaceSpecified {
        get {
            return this.datumZahajeniRealizaceFieldSpecified;
        }
        set {
            this.datumZahajeniRealizaceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime DatumUkonceniRealizace {
        get {
            return this.datumUkonceniRealizaceField;
        }
        set {
            this.datumUkonceniRealizaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DatumUkonceniRealizaceSpecified {
        get {
            return this.datumUkonceniRealizaceFieldSpecified;
        }
        set {
            this.datumUkonceniRealizaceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TMena Mena {
        get {
            return this.menaField;
        }
        set {
            this.menaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TPoloha {
    
    private double zemSirkaField;
    
    private double zemDelkaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double ZemSirka {
        get {
            return this.zemSirkaField;
        }
        set {
            this.zemSirkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double ZemDelka {
        get {
            return this.zemDelkaField;
        }
        set {
            this.zemDelkaField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TPenezniJednotka))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TJednotkaZavislaNaKontextu))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TOdvozenaJednotka))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TPojmenovanaJednotka))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TKonverzniJednotka))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TJednotkaSI))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public abstract partial class TJednotka {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TPenezniJednotka : TJednotka {
    
    private TMena menaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TMena Mena {
        get {
            return this.menaField;
        }
        set {
            this.menaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TMena {
    
    /// <remarks/>
    AED,
    
    /// <remarks/>
    AFN,
    
    /// <remarks/>
    ALL,
    
    /// <remarks/>
    AMD,
    
    /// <remarks/>
    ANG,
    
    /// <remarks/>
    AOA,
    
    /// <remarks/>
    ARS,
    
    /// <remarks/>
    AUD,
    
    /// <remarks/>
    AWG,
    
    /// <remarks/>
    AZN,
    
    /// <remarks/>
    BAM,
    
    /// <remarks/>
    BBD,
    
    /// <remarks/>
    BDT,
    
    /// <remarks/>
    BGN,
    
    /// <remarks/>
    BHD,
    
    /// <remarks/>
    BIF,
    
    /// <remarks/>
    BMD,
    
    /// <remarks/>
    BND,
    
    /// <remarks/>
    BOB,
    
    /// <remarks/>
    BOV,
    
    /// <remarks/>
    BRL,
    
    /// <remarks/>
    BSD,
    
    /// <remarks/>
    BTN,
    
    /// <remarks/>
    BWP,
    
    /// <remarks/>
    BYN,
    
    /// <remarks/>
    BZD,
    
    /// <remarks/>
    CAD,
    
    /// <remarks/>
    CDF,
    
    /// <remarks/>
    CHE,
    
    /// <remarks/>
    CHF,
    
    /// <remarks/>
    CHW,
    
    /// <remarks/>
    CLF,
    
    /// <remarks/>
    CLP,
    
    /// <remarks/>
    CNY,
    
    /// <remarks/>
    COP,
    
    /// <remarks/>
    COU,
    
    /// <remarks/>
    CRC,
    
    /// <remarks/>
    CUC,
    
    /// <remarks/>
    CUP,
    
    /// <remarks/>
    CVE,
    
    /// <remarks/>
    CZK,
    
    /// <remarks/>
    DJF,
    
    /// <remarks/>
    DKK,
    
    /// <remarks/>
    DOP,
    
    /// <remarks/>
    DZD,
    
    /// <remarks/>
    EGP,
    
    /// <remarks/>
    ERN,
    
    /// <remarks/>
    ETB,
    
    /// <remarks/>
    EUR,
    
    /// <remarks/>
    FJD,
    
    /// <remarks/>
    FKP,
    
    /// <remarks/>
    GBP,
    
    /// <remarks/>
    GEL,
    
    /// <remarks/>
    GHS,
    
    /// <remarks/>
    GIP,
    
    /// <remarks/>
    GMD,
    
    /// <remarks/>
    GNF,
    
    /// <remarks/>
    GTQ,
    
    /// <remarks/>
    GYD,
    
    /// <remarks/>
    HKD,
    
    /// <remarks/>
    HNL,
    
    /// <remarks/>
    HRK,
    
    /// <remarks/>
    HTG,
    
    /// <remarks/>
    HUF,
    
    /// <remarks/>
    IDR,
    
    /// <remarks/>
    ILS,
    
    /// <remarks/>
    INR,
    
    /// <remarks/>
    IQD,
    
    /// <remarks/>
    IRR,
    
    /// <remarks/>
    ISK,
    
    /// <remarks/>
    JMD,
    
    /// <remarks/>
    JOD,
    
    /// <remarks/>
    JPY,
    
    /// <remarks/>
    KES,
    
    /// <remarks/>
    KGS,
    
    /// <remarks/>
    KHR,
    
    /// <remarks/>
    KMF,
    
    /// <remarks/>
    KPW,
    
    /// <remarks/>
    KRW,
    
    /// <remarks/>
    KWD,
    
    /// <remarks/>
    KYD,
    
    /// <remarks/>
    KZT,
    
    /// <remarks/>
    LAK,
    
    /// <remarks/>
    LBP,
    
    /// <remarks/>
    LKR,
    
    /// <remarks/>
    LRD,
    
    /// <remarks/>
    LSL,
    
    /// <remarks/>
    LYD,
    
    /// <remarks/>
    MAD,
    
    /// <remarks/>
    MDL,
    
    /// <remarks/>
    MGA,
    
    /// <remarks/>
    MKD,
    
    /// <remarks/>
    MMK,
    
    /// <remarks/>
    MNT,
    
    /// <remarks/>
    MOP,
    
    /// <remarks/>
    MRU,
    
    /// <remarks/>
    MUR,
    
    /// <remarks/>
    MVR,
    
    /// <remarks/>
    MWK,
    
    /// <remarks/>
    MXN,
    
    /// <remarks/>
    MXV,
    
    /// <remarks/>
    MYR,
    
    /// <remarks/>
    MZN,
    
    /// <remarks/>
    NAD,
    
    /// <remarks/>
    NGN,
    
    /// <remarks/>
    NIO,
    
    /// <remarks/>
    NOK,
    
    /// <remarks/>
    NPR,
    
    /// <remarks/>
    NZD,
    
    /// <remarks/>
    OMR,
    
    /// <remarks/>
    PAB,
    
    /// <remarks/>
    PEN,
    
    /// <remarks/>
    PGK,
    
    /// <remarks/>
    PHP,
    
    /// <remarks/>
    PKR,
    
    /// <remarks/>
    PLN,
    
    /// <remarks/>
    PYG,
    
    /// <remarks/>
    QAR,
    
    /// <remarks/>
    RON,
    
    /// <remarks/>
    RSD,
    
    /// <remarks/>
    RUB,
    
    /// <remarks/>
    RWF,
    
    /// <remarks/>
    SAR,
    
    /// <remarks/>
    SBD,
    
    /// <remarks/>
    SCR,
    
    /// <remarks/>
    SDG,
    
    /// <remarks/>
    SEK,
    
    /// <remarks/>
    SGD,
    
    /// <remarks/>
    SHP,
    
    /// <remarks/>
    SLL,
    
    /// <remarks/>
    SOS,
    
    /// <remarks/>
    SRD,
    
    /// <remarks/>
    SSP,
    
    /// <remarks/>
    STN,
    
    /// <remarks/>
    SVC,
    
    /// <remarks/>
    SYP,
    
    /// <remarks/>
    SZL,
    
    /// <remarks/>
    THB,
    
    /// <remarks/>
    TJS,
    
    /// <remarks/>
    TMT,
    
    /// <remarks/>
    TND,
    
    /// <remarks/>
    TOP,
    
    /// <remarks/>
    TRY,
    
    /// <remarks/>
    TTD,
    
    /// <remarks/>
    TWD,
    
    /// <remarks/>
    TZS,
    
    /// <remarks/>
    UAH,
    
    /// <remarks/>
    UGX,
    
    /// <remarks/>
    USD,
    
    /// <remarks/>
    USN,
    
    /// <remarks/>
    UYI,
    
    /// <remarks/>
    UYU,
    
    /// <remarks/>
    UYW,
    
    /// <remarks/>
    UZS,
    
    /// <remarks/>
    VES,
    
    /// <remarks/>
    VND,
    
    /// <remarks/>
    VUV,
    
    /// <remarks/>
    WST,
    
    /// <remarks/>
    XAF,
    
    /// <remarks/>
    XAG,
    
    /// <remarks/>
    XAU,
    
    /// <remarks/>
    XBA,
    
    /// <remarks/>
    XBB,
    
    /// <remarks/>
    XBC,
    
    /// <remarks/>
    XBD,
    
    /// <remarks/>
    XCD,
    
    /// <remarks/>
    XDR,
    
    /// <remarks/>
    XOF,
    
    /// <remarks/>
    XPD,
    
    /// <remarks/>
    XPF,
    
    /// <remarks/>
    XPT,
    
    /// <remarks/>
    XSU,
    
    /// <remarks/>
    XTS,
    
    /// <remarks/>
    XUA,
    
    /// <remarks/>
    XXX,
    
    /// <remarks/>
    YER,
    
    /// <remarks/>
    ZAR,
    
    /// <remarks/>
    ZMW,
    
    /// <remarks/>
    ZWL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TJednotkaZavislaNaKontextu : TJednotka {
    
    private string nazevField;
    
    private string symbolField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Symbol {
        get {
            return this.symbolField;
        }
        set {
            this.symbolField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TOdvozenaJednotka : TJednotka {
    
    private TOdvozenaJednotkaComponenta[] componentaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Componenta")]
    public TOdvozenaJednotkaComponenta[] Componenta {
        get {
            return this.componentaField;
        }
        set {
            this.componentaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TOdvozenaJednotkaComponenta {
    
    private TPojmenovanaJednotka jednotkaField;
    
    private string exponentField;
    
    /// <remarks/>
    public TPojmenovanaJednotka Jednotka {
        get {
            return this.jednotkaField;
        }
        set {
            this.jednotkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Exponent {
        get {
            return this.exponentField;
        }
        set {
            this.exponentField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TKonverzniJednotka))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TJednotkaSI))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public abstract partial class TPojmenovanaJednotka : TJednotka {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TKonverzniJednotka : TPojmenovanaJednotka {
    
    private TJednotkaSI zakladniJednotkaField;
    
    private string nazevField;
    
    private string symbolField;
    
    private double meritkoField;
    
    private double odsazeniField;
    
    public TKonverzniJednotka() {
        this.meritkoField = 1D;
        this.odsazeniField = 0D;
    }
    
    /// <remarks/>
    public TJednotkaSI ZakladniJednotka {
        get {
            return this.zakladniJednotkaField;
        }
        set {
            this.zakladniJednotkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Symbol {
        get {
            return this.symbolField;
        }
        set {
            this.symbolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(1D)]
    public double Meritko {
        get {
            return this.meritkoField;
        }
        set {
            this.meritkoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double Odsazeni {
        get {
            return this.odsazeniField;
        }
        set {
            this.odsazeniField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TJednotkaSI : TPojmenovanaJednotka {
    
    private TNazevJednotkySI nazevField;
    
    private TPredponaSI predponaField;
    
    private bool predponaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TNazevJednotkySI Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TPredponaSI Predpona {
        get {
            return this.predponaField;
        }
        set {
            this.predponaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PredponaSpecified {
        get {
            return this.predponaFieldSpecified;
        }
        set {
            this.predponaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TNazevJednotkySI {
    
    /// <remarks/>
    metre,
    
    /// <remarks/>
    kilogram,
    
    /// <remarks/>
    second,
    
    /// <remarks/>
    ampere,
    
    /// <remarks/>
    kelvin,
    
    /// <remarks/>
    mole,
    
    /// <remarks/>
    candela,
    
    /// <remarks/>
    radian,
    
    /// <remarks/>
    steradian,
    
    /// <remarks/>
    hertz,
    
    /// <remarks/>
    newton,
    
    /// <remarks/>
    pascal,
    
    /// <remarks/>
    joule,
    
    /// <remarks/>
    watt,
    
    /// <remarks/>
    coulomb,
    
    /// <remarks/>
    volt,
    
    /// <remarks/>
    farad,
    
    /// <remarks/>
    ohm,
    
    /// <remarks/>
    siemens,
    
    /// <remarks/>
    weber,
    
    /// <remarks/>
    tesla,
    
    /// <remarks/>
    henry,
    
    /// <remarks/>
    degree_Celsius,
    
    /// <remarks/>
    lumen,
    
    /// <remarks/>
    lux,
    
    /// <remarks/>
    becquerel,
    
    /// <remarks/>
    gray,
    
    /// <remarks/>
    sievert,
    
    /// <remarks/>
    katal,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TPredponaSI {
    
    /// <remarks/>
    yotta,
    
    /// <remarks/>
    zetta,
    
    /// <remarks/>
    exa,
    
    /// <remarks/>
    peta,
    
    /// <remarks/>
    tera,
    
    /// <remarks/>
    giga,
    
    /// <remarks/>
    mega,
    
    /// <remarks/>
    kilo,
    
    /// <remarks/>
    hecto,
    
    /// <remarks/>
    deca,
    
    /// <remarks/>
    deci,
    
    /// <remarks/>
    centi,
    
    /// <remarks/>
    milli,
    
    /// <remarks/>
    micro,
    
    /// <remarks/>
    nano,
    
    /// <remarks/>
    pico,
    
    /// <remarks/>
    femto,
    
    /// <remarks/>
    atto,
    
    /// <remarks/>
    zepto,
    
    /// <remarks/>
    yocto,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TCenovaSoustava {
    
    private string idField;
    
    private string nazevField;
    
    private string popisField;
    
    private string zdrojField;
    
    private string umisteniField;
    
    private string ediceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Zdroj {
        get {
            return this.zdrojField;
        }
        set {
            this.zdrojField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Umisteni {
        get {
            return this.umisteniField;
        }
        set {
            this.umisteniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Edice {
        get {
            return this.ediceField;
        }
        set {
            this.ediceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TTrida {
    
    private TTrida[] tridaField;
    
    private string idField;
    
    private string kodField;
    
    private string nazevField;
    
    private string popisField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trida")]
    public TTrida[] Trida {
        get {
            return this.tridaField;
        }
        set {
            this.tridaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TKlasifikace {
    
    private TTrida[] tridaField;
    
    private TTypKlasifikace typField;
    
    private string nazevField;
    
    private string popisField;
    
    private string zdrojField;
    
    private string umisteniField;
    
    private string ediceField;
    
    public TKlasifikace() {
        this.typField = TTypKlasifikace.Vlastni;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trida")]
    public TTrida[] Trida {
        get {
            return this.tridaField;
        }
        set {
            this.tridaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(TTypKlasifikace.Vlastni)]
    public TTypKlasifikace Typ {
        get {
            return this.typField;
        }
        set {
            this.typField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Zdroj {
        get {
            return this.zdrojField;
        }
        set {
            this.zdrojField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Umisteni {
        get {
            return this.umisteniField;
        }
        set {
            this.umisteniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Edice {
        get {
            return this.ediceField;
        }
        set {
            this.ediceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TTypKlasifikace {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CC - CZ")]
    CCCZ,
    
    /// <remarks/>
    CPV,
    
    /// <remarks/>
    CPA,
    
    /// <remarks/>
    Vlastni,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TOsoba {
    
    private string adresaField;
    
    private string jmenoField;
    
    private string emailField;
    
    /// <remarks/>
    public string Adresa {
        get {
            return this.adresaField;
        }
        set {
            this.adresaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Jmeno {
        get {
            return this.jmenoField;
        }
        set {
            this.jmenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TOrganizace {
    
    private string adresaField;
    
    private TOsoba kontaktField;
    
    private string idField;
    
    private string nazevField;
    
    private string statField;
    
    private string iCOField;
    
    private string dICField;
    
    private string pSCField;
    
    private string telefonField;
    
    private string emailField;
    
    /// <remarks/>
    public string Adresa {
        get {
            return this.adresaField;
        }
        set {
            this.adresaField = value;
        }
    }
    
    /// <remarks/>
    public TOsoba Kontakt {
        get {
            return this.kontaktField;
        }
        set {
            this.kontaktField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Stat {
        get {
            return this.statField;
        }
        set {
            this.statField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ICO {
        get {
            return this.iCOField;
        }
        set {
            this.iCOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DIC {
        get {
            return this.dICField;
        }
        set {
            this.dICField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PSC {
        get {
            return this.pSCField;
        }
        set {
            this.pSCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Telefon {
        get {
            return this.telefonField;
        }
        set {
            this.telefonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TDefinice {
    
    private TOrganizace[] organizaceField;
    
    private TKlasifikace[] klasifikaceField;
    
    private TCenovaSoustava[] cenovaSoustavaField;
    
    private TJednotka[] jednotkaField;
    
    private string zaokrouhleniMnozstviPolozkyField;
    
    private bool pozadovanaSazbaDPHField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Organizace")]
    public TOrganizace[] Organizace {
        get {
            return this.organizaceField;
        }
        set {
            this.organizaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Klasifikace")]
    public TKlasifikace[] Klasifikace {
        get {
            return this.klasifikaceField;
        }
        set {
            this.klasifikaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CenovaSoustava")]
    public TCenovaSoustava[] CenovaSoustava {
        get {
            return this.cenovaSoustavaField;
        }
        set {
            this.cenovaSoustavaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Jednotka")]
    public TJednotka[] Jednotka {
        get {
            return this.jednotkaField;
        }
        set {
            this.jednotkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string ZaokrouhleniMnozstviPolozky {
        get {
            return this.zaokrouhleniMnozstviPolozkyField;
        }
        set {
            this.zaokrouhleniMnozstviPolozkyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool PozadovanaSazbaDPH {
        get {
            return this.pozadovanaSazbaDPHField;
        }
        set {
            this.pozadovanaSazbaDPHField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TOrganizaceRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TJednotkovaCena {
    
    private TOrganizaceRef autorField;
    
    private string komentarField;
    
    private decimal cenaField;
    
    private System.DateTime datumField;
    
    /// <remarks/>
    public TOrganizaceRef Autor {
        get {
            return this.autorField;
        }
        set {
            this.autorField = value;
        }
    }
    
    /// <remarks/>
    public string Komentar {
        get {
            return this.komentarField;
        }
        set {
            this.komentarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Cena {
        get {
            return this.cenaField;
        }
        set {
            this.cenaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TJednotkaRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TMnozstvi {
    
    private string vymeraField;
    
    private TJednotkaRef jednotkaField;
    
    private string skupinaMereniField;
    
    private decimal hodnotaField;
    
    /// <remarks/>
    public string Vymera {
        get {
            return this.vymeraField;
        }
        set {
            this.vymeraField = value;
        }
    }
    
    /// <remarks/>
    public TJednotkaRef Jednotka {
        get {
            return this.jednotkaField;
        }
        set {
            this.jednotkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SkupinaMereni {
        get {
            return this.skupinaMereniField;
        }
        set {
            this.skupinaMereniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Hodnota {
        get {
            return this.hodnotaField;
        }
        set {
            this.hodnotaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TCenovaSoustavaRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TTridaRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TExterniEntita {
    
    private string idField;
    
    private string nazevField;
    
    private string zdrojField;
    
    private string umisteniField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Zdroj {
        get {
            return this.zdrojField;
        }
        set {
            this.zdrojField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Umisteni {
        get {
            return this.umisteniField;
        }
        set {
            this.umisteniField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TPolozkaRozpoctu))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TUzelRozpoctu))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TObjekt))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TRozpocet))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TProjekt))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public abstract partial class TIdentita {
    
    private string popisField;
    
    private TExterniEntita[] externiEntitaField;
    
    private string idField;
    
    private string nazevField;
    
    private string dlouhyNazevField;
    
    /// <remarks/>
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExterniEntita")]
    public TExterniEntita[] ExterniEntita {
        get {
            return this.externiEntitaField;
        }
        set {
            this.externiEntitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DlouhyNazev {
        get {
            return this.dlouhyNazevField;
        }
        set {
            this.dlouhyNazevField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TPolozkaRozpoctu : TIdentita {
    
    private TTridaRef[] zatrideniField;
    
    private TCenovaSoustavaRef cenovaSoustavaField;
    
    private TMnozstvi mnozstviField;
    
    private TExterniEntita[] souvisejiciEntitaField;
    
    private string komentarField;
    
    private TJednotkovaCena jednotkovaCenaField;
    
    private string kodField;
    
    private string poradoveCisloField;
    
    private TTypPolozky typField;
    
    private double jednotkovaHmotnostField;
    
    private bool jednotkovaHmotnostFieldSpecified;
    
    private double jednotkovaDemontazniHmotnostField;
    
    private bool jednotkovaDemontazniHmotnostFieldSpecified;
    
    private decimal sazbaDPHField;
    
    private bool sazbaDPHFieldSpecified;
    
    private bool prenesenaDPHField;
    
    private bool prenesenaDPHFieldSpecified;
    
    private bool pouzeMaterialField;
    
    private bool pouzeMaterialFieldSpecified;
    
    private string variantaField;
    
    private string zpusobilostField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Zatrideni")]
    public TTridaRef[] Zatrideni {
        get {
            return this.zatrideniField;
        }
        set {
            this.zatrideniField = value;
        }
    }
    
    /// <remarks/>
    public TCenovaSoustavaRef CenovaSoustava {
        get {
            return this.cenovaSoustavaField;
        }
        set {
            this.cenovaSoustavaField = value;
        }
    }
    
    /// <remarks/>
    public TMnozstvi Mnozstvi {
        get {
            return this.mnozstviField;
        }
        set {
            this.mnozstviField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SouvisejiciEntita")]
    public TExterniEntita[] SouvisejiciEntita {
        get {
            return this.souvisejiciEntitaField;
        }
        set {
            this.souvisejiciEntitaField = value;
        }
    }
    
    /// <remarks/>
    public string Komentar {
        get {
            return this.komentarField;
        }
        set {
            this.komentarField = value;
        }
    }
    
    /// <remarks/>
    public TJednotkovaCena JednotkovaCena {
        get {
            return this.jednotkovaCenaField;
        }
        set {
            this.jednotkovaCenaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string PoradoveCislo {
        get {
            return this.poradoveCisloField;
        }
        set {
            this.poradoveCisloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TTypPolozky Typ {
        get {
            return this.typField;
        }
        set {
            this.typField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double JednotkovaHmotnost {
        get {
            return this.jednotkovaHmotnostField;
        }
        set {
            this.jednotkovaHmotnostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool JednotkovaHmotnostSpecified {
        get {
            return this.jednotkovaHmotnostFieldSpecified;
        }
        set {
            this.jednotkovaHmotnostFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double JednotkovaDemontazniHmotnost {
        get {
            return this.jednotkovaDemontazniHmotnostField;
        }
        set {
            this.jednotkovaDemontazniHmotnostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool JednotkovaDemontazniHmotnostSpecified {
        get {
            return this.jednotkovaDemontazniHmotnostFieldSpecified;
        }
        set {
            this.jednotkovaDemontazniHmotnostFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal SazbaDPH {
        get {
            return this.sazbaDPHField;
        }
        set {
            this.sazbaDPHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SazbaDPHSpecified {
        get {
            return this.sazbaDPHFieldSpecified;
        }
        set {
            this.sazbaDPHFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool PrenesenaDPH {
        get {
            return this.prenesenaDPHField;
        }
        set {
            this.prenesenaDPHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrenesenaDPHSpecified {
        get {
            return this.prenesenaDPHFieldSpecified;
        }
        set {
            this.prenesenaDPHFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool PouzeMaterial {
        get {
            return this.pouzeMaterialField;
        }
        set {
            this.pouzeMaterialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PouzeMaterialSpecified {
        get {
            return this.pouzeMaterialFieldSpecified;
        }
        set {
            this.pouzeMaterialFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Varianta {
        get {
            return this.variantaField;
        }
        set {
            this.variantaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Zpusobilost {
        get {
            return this.zpusobilostField;
        }
        set {
            this.zpusobilostField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TTypPolozky {
    
    /// <remarks/>
    HSV,
    
    /// <remarks/>
    PSV,
    
    /// <remarks/>
    M,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TObjekt))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TUzelRozpoctu : TIdentita {
    
    private TTridaRef[] zatrideniField;
    
    private TUzelRozpoctu[] uzelRozpoctuField;
    
    private TPolozkaRozpoctu[] polozkaField;
    
    private string vlastniTypField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Zatrideni")]
    public TTridaRef[] Zatrideni {
        get {
            return this.zatrideniField;
        }
        set {
            this.zatrideniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UzelRozpoctu")]
    public TUzelRozpoctu[] UzelRozpoctu {
        get {
            return this.uzelRozpoctuField;
        }
        set {
            this.uzelRozpoctuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Polozka")]
    public TPolozkaRozpoctu[] Polozka {
        get {
            return this.polozkaField;
        }
        set {
            this.polozkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VlastniTyp {
        get {
            return this.vlastniTypField;
        }
        set {
            this.vlastniTypField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TObjekt : TUzelRozpoctu {
    
    private string kSOField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string KSO {
        get {
            return this.kSOField;
        }
        set {
            this.kSOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TRozpocet : TIdentita {
    
    private TObjekt[] objektField;
    
    private TOrganizaceRef objednatelField;
    
    private TOrganizaceRef autorField;
    
    private System.DateTime datumField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Objekt")]
    public TObjekt[] Objekt {
        get {
            return this.objektField;
        }
        set {
            this.objektField = value;
        }
    }
    
    /// <remarks/>
    public TOrganizaceRef Objednatel {
        get {
            return this.objednatelField;
        }
        set {
            this.objednatelField = value;
        }
    }
    
    /// <remarks/>
    public TOrganizaceRef Autor {
        get {
            return this.autorField;
        }
        set {
            this.autorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TVerze {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("v0.1")]
    v01,
}
