// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.90.0. www.xsd2code.com
//    {"TargetFramework":"NetStandard","NameSpace":"ORF.XML.MathML","ExpandNestedAttributeGroup":true,"Properties":{"AutomaticProperties":true,"PascalCaseProperty":true},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ORF.XML.MathML
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(TypeName = "mrowtype", Namespace = "http://www.w3.org/1998/Math/MathML")]
    [XmlRootAttribute("mrow", Namespace = "http://www.w3.org/1998/Math/MathML", IsNullable = false, ElementName = "mrowtype")]
    public partial class Mrowtype
    {
        [XmlElement("apply", typeof(Applytype))]
        [XmlElement("ci", typeof(Citype))]
        [XmlElement("cn", typeof(Cntype))]
        [XmlElement("eulergamma", typeof(Citype))]
        [XmlElement("pi", typeof(Citype))]
        [XmlElement("semantics", typeof(Semanticstype))]
        [XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item { get; set; }
        [XmlIgnore]
        public ItemChoiceType2 ItemElementName { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(TypeName = "applytype", Namespace = "http://www.w3.org/1998/Math/MathML")]
    [XmlRootAttribute("apply", Namespace = "http://www.w3.org/1998/Math/MathML", IsNullable = false, ElementName = "applytype")]
    public partial class Applytype
    {
        [XmlElement("abs", typeof(Csymboltype))]
        [XmlElement("arccos", typeof(Csymboltype))]
        [XmlElement("arccosh", typeof(Csymboltype))]
        [XmlElement("arccot", typeof(Csymboltype))]
        [XmlElement("arccoth", typeof(Csymboltype))]
        [XmlElement("arccsc", typeof(Csymboltype))]
        [XmlElement("arccsch", typeof(Csymboltype))]
        [XmlElement("arcsec", typeof(Csymboltype))]
        [XmlElement("arcsech", typeof(Csymboltype))]
        [XmlElement("arcsin", typeof(Csymboltype))]
        [XmlElement("arcsinh", typeof(Csymboltype))]
        [XmlElement("arctan", typeof(Csymboltype))]
        [XmlElement("arctanh", typeof(Csymboltype))]
        [XmlElement("ceiling", typeof(Csymboltype))]
        [XmlElement("cos", typeof(Csymboltype))]
        [XmlElement("cosh", typeof(Csymboltype))]
        [XmlElement("cot", typeof(Csymboltype))]
        [XmlElement("coth", typeof(Csymboltype))]
        [XmlElement("csc", typeof(Csymboltype))]
        [XmlElement("csch", typeof(Csymboltype))]
        [XmlElement("csymbol", typeof(Csymboltype))]
        [XmlElement("divide", typeof(Csymboltype))]
        [XmlElement("exp", typeof(Csymboltype))]
        [XmlElement("floor", typeof(Csymboltype))]
        [XmlElement("gcd", typeof(Csymboltype))]
        [XmlElement("lcm", typeof(Csymboltype))]
        [XmlElement("ln", typeof(Csymboltype))]
        [XmlElement("log", typeof(Csymboltype))]
        [XmlElement("max", typeof(Csymboltype))]
        [XmlElement("min", typeof(Csymboltype))]
        [XmlElement("minus", typeof(Csymboltype))]
        [XmlElement("plus", typeof(Csymboltype))]
        [XmlElement("power", typeof(Csymboltype))]
        [XmlElement("quotient", typeof(Csymboltype))]
        [XmlElement("rem", typeof(Csymboltype))]
        [XmlElement("root", typeof(Csymboltype))]
        [XmlElement("sec", typeof(Csymboltype))]
        [XmlElement("sech", typeof(Csymboltype))]
        [XmlElement("sin", typeof(Csymboltype))]
        [XmlElement("sinh", typeof(Csymboltype))]
        [XmlElement("sum", typeof(Csymboltype))]
        [XmlElement("tan", typeof(Csymboltype))]
        [XmlElement("tanh", typeof(Csymboltype))]
        [XmlElement("times", typeof(Csymboltype))]
        [XmlChoiceIdentifierAttribute("ItemElementName")]
        public Csymboltype Item { get; set; }
        [XmlIgnore]
        public ItemChoiceType ItemElementName { get; set; }
        [XmlElement("apply", typeof(Applytype))]
        [XmlElement("ci", typeof(Citype))]
        [XmlElement("cn", typeof(Cntype))]
        [XmlElement("eulergamma", typeof(Citype))]
        [XmlElement("pi", typeof(Citype))]
        [XmlElement("semantics", typeof(Semanticstype))]
        [XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items { get; set; }
        [XmlElement("ItemsElementName")]
        [XmlIgnore]
        public ItemsChoiceType[] ItemsElementName { get; set; }
        [XmlAttribute(DataType = "ID", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(AttributeName = "xref")]
        public string Xref { get; set; }
        [XmlAttribute(DataType = "anyURI", AttributeName = "href")]
        public string Href { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(TypeName = "csymboltype", Namespace = "http://www.w3.org/1998/Math/MathML")]
    [XmlRootAttribute("csymbol", Namespace = "http://www.w3.org/1998/Math/MathML", IsNullable = false, ElementName = "csymboltype")]
    public partial class Csymboltype
    {
        [XmlAttribute(DataType = "ID", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(AttributeName = "xref")]
        public string Xref { get; set; }
        [XmlAttribute(DataType = "anyURI", AttributeName = "href")]
        public string Href { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(TypeName = "semanticstype", Namespace = "http://www.w3.org/1998/Math/MathML")]
    [XmlRootAttribute("semantics", Namespace = "http://www.w3.org/1998/Math/MathML", IsNullable = false, ElementName = "semanticstype")]
    public partial class Semanticstype
    {
        [XmlElement("apply", typeof(Applytype))]
        [XmlElement("ci", typeof(Citype))]
        [XmlElement("cn", typeof(Cntype))]
        [XmlElement("eulergamma", typeof(Citype))]
        [XmlElement("pi", typeof(Citype))]
        [XmlElement("semantics", typeof(Semanticstype))]
        [XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item { get; set; }
        [XmlIgnore]
        public ItemChoiceType1 ItemElementName { get; set; }
        [XmlElement("annotation")]
        public List<object> Items { get; set; }
        [XmlAttribute(DataType = "ID", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(AttributeName = "xref")]
        public string Xref { get; set; }
        [XmlAttribute(DataType = "anyURI", AttributeName = "href")]
        public string Href { get; set; }

        public Semanticstype()
        {
            Items = new List<object>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(TypeName = "citype", Namespace = "http://www.w3.org/1998/Math/MathML")]
    [XmlRootAttribute("ci", Namespace = "http://www.w3.org/1998/Math/MathML", IsNullable = false, ElementName = "citype")]
    public partial class Citype
    {
        [XmlAttribute(DataType = "ID", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(AttributeName = "xref")]
        public string Xref { get; set; }
        [XmlAttribute(DataType = "anyURI", AttributeName = "href")]
        public string Href { get; set; }
        [XmlAttribute(AttributeName = "type")]
        public CitypeType Type { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/1998/Math/MathML", TypeName = "citypeType")]
    [XmlRootAttribute("citypeType")]
    public enum CitypeType
    {
        integer,
        real,
        constant,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(TypeName = "cntype", Namespace = "http://www.w3.org/1998/Math/MathML")]
    [XmlRootAttribute("cn", Namespace = "http://www.w3.org/1998/Math/MathML", IsNullable = false, ElementName = "cntype")]
    public partial class Cntype
    {
        [XmlAttribute(DataType = "ID", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(AttributeName = "xref")]
        public string Xref { get; set; }
        [XmlAttribute(DataType = "anyURI", AttributeName = "href")]
        public string Href { get; set; }
        [XmlAttribute(AttributeName = "type")]
        public CntypeType Type { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/1998/Math/MathML", TypeName = "cntypeType")]
    [XmlRootAttribute("cntypeType")]
    public enum CntypeType
    {
        integer,
        real,
        @double,
        hexdouble,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/1998/Math/MathML", IncludeInSchema = false)]
    [XmlRootAttribute("ItemChoiceType1")]
    public enum ItemChoiceType1
    {
        apply,
        ci,
        cn,
        eulergamma,
        pi,
        semantics,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/1998/Math/MathML", IncludeInSchema = false)]
    [XmlRootAttribute("ItemChoiceType")]
    public enum ItemChoiceType
    {
        abs,
        arccos,
        arccosh,
        arccot,
        arccoth,
        arccsc,
        arccsch,
        arcsec,
        arcsech,
        arcsin,
        arcsinh,
        arctan,
        arctanh,
        ceiling,
        cos,
        cosh,
        cot,
        coth,
        csc,
        csch,
        csymbol,
        divide,
        exp,
        floor,
        gcd,
        lcm,
        ln,
        log,
        max,
        min,
        minus,
        plus,
        power,
        quotient,
        rem,
        root,
        sec,
        sech,
        sin,
        sinh,
        sum,
        tan,
        tanh,
        times,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/1998/Math/MathML", IncludeInSchema = false)]
    [XmlRootAttribute("ItemsChoiceType")]
    public enum ItemsChoiceType
    {
        apply,
        ci,
        cn,
        eulergamma,
        pi,
        semantics,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/1998/Math/MathML", IncludeInSchema = false)]
    [XmlRootAttribute("ItemChoiceType2")]
    public enum ItemChoiceType2
    {
        apply,
        ci,
        cn,
        eulergamma,
        pi,
        semantics,
    }
}
#pragma warning restore
