//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
[System.Xml.Serialization.XmlRootAttribute("ORF", Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd", IsNullable=false)]
public partial class TORF {
    
    private TProjekt projektField;
    
    private TRozpocet rozpocetField;
    
    private TDefinice definiceField;
    
    private TVerze verzeField;
    
    /// <remarks/>
    public TProjekt Projekt {
        get {
            return this.projektField;
        }
        set {
            this.projektField = value;
        }
    }
    
    /// <remarks/>
    public TRozpocet Rozpocet {
        get {
            return this.rozpocetField;
        }
        set {
            this.rozpocetField = value;
        }
    }
    
    /// <remarks/>
    public TDefinice Definice {
        get {
            return this.definiceField;
        }
        set {
            this.definiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TVerze Verze {
        get {
            return this.verzeField;
        }
        set {
            this.verzeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TProjekt : TIdentita {
    
    private TAdresa adresaField;
    
    private TPoloha umisteniField;
    
    private string evidencniCisloField;
    
    private TMena menaField;
    
    /// <remarks/>
    public TAdresa Adresa {
        get {
            return this.adresaField;
        }
        set {
            this.adresaField = value;
        }
    }
    
    /// <remarks/>
    public TPoloha Umisteni {
        get {
            return this.umisteniField;
        }
        set {
            this.umisteniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EvidencniCislo {
        get {
            return this.evidencniCisloField;
        }
        set {
            this.evidencniCisloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TMena Mena {
        get {
            return this.menaField;
        }
        set {
            this.menaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TAdresa {
    
    private string uliceACisloField;
    
    private string castObceField;
    
    private string obecField;
    
    private string pSCField;
    
    private string statField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UliceACislo {
        get {
            return this.uliceACisloField;
        }
        set {
            this.uliceACisloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CastObce {
        get {
            return this.castObceField;
        }
        set {
            this.castObceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Obec {
        get {
            return this.obecField;
        }
        set {
            this.obecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PSC {
        get {
            return this.pSCField;
        }
        set {
            this.pSCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Stat {
        get {
            return this.statField;
        }
        set {
            this.statField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TMetodikaMereni {
    
    private TJednotkaRef mernaJednotkaField;
    
    private string idField;
    
    private string znackaField;
    
    private string popisField;
    
    private string podrobnyPopisField;
    
    /// <remarks/>
    public TJednotkaRef MernaJednotka {
        get {
            return this.mernaJednotkaField;
        }
        set {
            this.mernaJednotkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Znacka {
        get {
            return this.znackaField;
        }
        set {
            this.znackaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PodrobnyPopis {
        get {
            return this.podrobnyPopisField;
        }
        set {
            this.podrobnyPopisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TJednotkaRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TSazbaDPH {
    
    private string popisField;
    
    private string idField;
    
    private decimal sazbaDPHField;
    
    private bool sazbaDPHFieldSpecified;
    
    /// <remarks/>
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal SazbaDPH {
        get {
            return this.sazbaDPHField;
        }
        set {
            this.sazbaDPHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SazbaDPHSpecified {
        get {
            return this.sazbaDPHFieldSpecified;
        }
        set {
            this.sazbaDPHFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TKomponentaJednotky {
    
    private TJednotka jednotkaField;
    
    private int exponentField;
    
    /// <remarks/>
    public TJednotka Jednotka {
        get {
            return this.jednotkaField;
        }
        set {
            this.jednotkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Exponent {
        get {
            return this.exponentField;
        }
        set {
            this.exponentField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TPenezniJednotka))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TJednotkaZavislaNaKontextu))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TKonverzniJednotka))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TOdvozenaJednotka))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TJednotkaSI))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public abstract partial class TJednotka {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TPenezniJednotka : TJednotka {
    
    private TMena menaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TMena Mena {
        get {
            return this.menaField;
        }
        set {
            this.menaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TMena {
    
    /// <remarks/>
    AED,
    
    /// <remarks/>
    AFN,
    
    /// <remarks/>
    ALL,
    
    /// <remarks/>
    AMD,
    
    /// <remarks/>
    ANG,
    
    /// <remarks/>
    AOA,
    
    /// <remarks/>
    ARS,
    
    /// <remarks/>
    AUD,
    
    /// <remarks/>
    AWG,
    
    /// <remarks/>
    AZN,
    
    /// <remarks/>
    BAM,
    
    /// <remarks/>
    BBD,
    
    /// <remarks/>
    BDT,
    
    /// <remarks/>
    BGN,
    
    /// <remarks/>
    BHD,
    
    /// <remarks/>
    BIF,
    
    /// <remarks/>
    BMD,
    
    /// <remarks/>
    BND,
    
    /// <remarks/>
    BOB,
    
    /// <remarks/>
    BOV,
    
    /// <remarks/>
    BRL,
    
    /// <remarks/>
    BSD,
    
    /// <remarks/>
    BTN,
    
    /// <remarks/>
    BWP,
    
    /// <remarks/>
    BYN,
    
    /// <remarks/>
    BZD,
    
    /// <remarks/>
    CAD,
    
    /// <remarks/>
    CDF,
    
    /// <remarks/>
    CHE,
    
    /// <remarks/>
    CHF,
    
    /// <remarks/>
    CHW,
    
    /// <remarks/>
    CLF,
    
    /// <remarks/>
    CLP,
    
    /// <remarks/>
    CNY,
    
    /// <remarks/>
    COP,
    
    /// <remarks/>
    COU,
    
    /// <remarks/>
    CRC,
    
    /// <remarks/>
    CUC,
    
    /// <remarks/>
    CUP,
    
    /// <remarks/>
    CVE,
    
    /// <remarks/>
    CZK,
    
    /// <remarks/>
    DJF,
    
    /// <remarks/>
    DKK,
    
    /// <remarks/>
    DOP,
    
    /// <remarks/>
    DZD,
    
    /// <remarks/>
    EGP,
    
    /// <remarks/>
    ERN,
    
    /// <remarks/>
    ETB,
    
    /// <remarks/>
    EUR,
    
    /// <remarks/>
    FJD,
    
    /// <remarks/>
    FKP,
    
    /// <remarks/>
    GBP,
    
    /// <remarks/>
    GEL,
    
    /// <remarks/>
    GHS,
    
    /// <remarks/>
    GIP,
    
    /// <remarks/>
    GMD,
    
    /// <remarks/>
    GNF,
    
    /// <remarks/>
    GTQ,
    
    /// <remarks/>
    GYD,
    
    /// <remarks/>
    HKD,
    
    /// <remarks/>
    HNL,
    
    /// <remarks/>
    HRK,
    
    /// <remarks/>
    HTG,
    
    /// <remarks/>
    HUF,
    
    /// <remarks/>
    IDR,
    
    /// <remarks/>
    ILS,
    
    /// <remarks/>
    INR,
    
    /// <remarks/>
    IQD,
    
    /// <remarks/>
    IRR,
    
    /// <remarks/>
    ISK,
    
    /// <remarks/>
    JMD,
    
    /// <remarks/>
    JOD,
    
    /// <remarks/>
    JPY,
    
    /// <remarks/>
    KES,
    
    /// <remarks/>
    KGS,
    
    /// <remarks/>
    KHR,
    
    /// <remarks/>
    KMF,
    
    /// <remarks/>
    KPW,
    
    /// <remarks/>
    KRW,
    
    /// <remarks/>
    KWD,
    
    /// <remarks/>
    KYD,
    
    /// <remarks/>
    KZT,
    
    /// <remarks/>
    LAK,
    
    /// <remarks/>
    LBP,
    
    /// <remarks/>
    LKR,
    
    /// <remarks/>
    LRD,
    
    /// <remarks/>
    LSL,
    
    /// <remarks/>
    LYD,
    
    /// <remarks/>
    MAD,
    
    /// <remarks/>
    MDL,
    
    /// <remarks/>
    MGA,
    
    /// <remarks/>
    MKD,
    
    /// <remarks/>
    MMK,
    
    /// <remarks/>
    MNT,
    
    /// <remarks/>
    MOP,
    
    /// <remarks/>
    MRU,
    
    /// <remarks/>
    MUR,
    
    /// <remarks/>
    MVR,
    
    /// <remarks/>
    MWK,
    
    /// <remarks/>
    MXN,
    
    /// <remarks/>
    MXV,
    
    /// <remarks/>
    MYR,
    
    /// <remarks/>
    MZN,
    
    /// <remarks/>
    NAD,
    
    /// <remarks/>
    NGN,
    
    /// <remarks/>
    NIO,
    
    /// <remarks/>
    NOK,
    
    /// <remarks/>
    NPR,
    
    /// <remarks/>
    NZD,
    
    /// <remarks/>
    OMR,
    
    /// <remarks/>
    PAB,
    
    /// <remarks/>
    PEN,
    
    /// <remarks/>
    PGK,
    
    /// <remarks/>
    PHP,
    
    /// <remarks/>
    PKR,
    
    /// <remarks/>
    PLN,
    
    /// <remarks/>
    PYG,
    
    /// <remarks/>
    QAR,
    
    /// <remarks/>
    RON,
    
    /// <remarks/>
    RSD,
    
    /// <remarks/>
    RUB,
    
    /// <remarks/>
    RWF,
    
    /// <remarks/>
    SAR,
    
    /// <remarks/>
    SBD,
    
    /// <remarks/>
    SCR,
    
    /// <remarks/>
    SDG,
    
    /// <remarks/>
    SEK,
    
    /// <remarks/>
    SGD,
    
    /// <remarks/>
    SHP,
    
    /// <remarks/>
    SLL,
    
    /// <remarks/>
    SOS,
    
    /// <remarks/>
    SRD,
    
    /// <remarks/>
    SSP,
    
    /// <remarks/>
    STN,
    
    /// <remarks/>
    SVC,
    
    /// <remarks/>
    SYP,
    
    /// <remarks/>
    SZL,
    
    /// <remarks/>
    THB,
    
    /// <remarks/>
    TJS,
    
    /// <remarks/>
    TMT,
    
    /// <remarks/>
    TND,
    
    /// <remarks/>
    TOP,
    
    /// <remarks/>
    TRY,
    
    /// <remarks/>
    TTD,
    
    /// <remarks/>
    TWD,
    
    /// <remarks/>
    TZS,
    
    /// <remarks/>
    UAH,
    
    /// <remarks/>
    UGX,
    
    /// <remarks/>
    USD,
    
    /// <remarks/>
    USN,
    
    /// <remarks/>
    UYI,
    
    /// <remarks/>
    UYU,
    
    /// <remarks/>
    UYW,
    
    /// <remarks/>
    UZS,
    
    /// <remarks/>
    VES,
    
    /// <remarks/>
    VND,
    
    /// <remarks/>
    VUV,
    
    /// <remarks/>
    WST,
    
    /// <remarks/>
    XAF,
    
    /// <remarks/>
    XAG,
    
    /// <remarks/>
    XAU,
    
    /// <remarks/>
    XBA,
    
    /// <remarks/>
    XBB,
    
    /// <remarks/>
    XBC,
    
    /// <remarks/>
    XBD,
    
    /// <remarks/>
    XCD,
    
    /// <remarks/>
    XDR,
    
    /// <remarks/>
    XOF,
    
    /// <remarks/>
    XPD,
    
    /// <remarks/>
    XPF,
    
    /// <remarks/>
    XPT,
    
    /// <remarks/>
    XSU,
    
    /// <remarks/>
    XTS,
    
    /// <remarks/>
    XUA,
    
    /// <remarks/>
    XXX,
    
    /// <remarks/>
    YER,
    
    /// <remarks/>
    ZAR,
    
    /// <remarks/>
    ZMW,
    
    /// <remarks/>
    ZWL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TJednotkaZavislaNaKontextu : TJednotka {
    
    private string nazevField;
    
    private string symbolField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Symbol {
        get {
            return this.symbolField;
        }
        set {
            this.symbolField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TKonverzniJednotka : TJednotka {
    
    private TJednotkaSI zakladniJednotkaField;
    
    private string nazevField;
    
    private string symbolField;
    
    private double meritkoField;
    
    private double odsazeniField;
    
    public TKonverzniJednotka() {
        this.meritkoField = 1D;
        this.odsazeniField = 0D;
    }
    
    /// <remarks/>
    public TJednotkaSI ZakladniJednotka {
        get {
            return this.zakladniJednotkaField;
        }
        set {
            this.zakladniJednotkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Symbol {
        get {
            return this.symbolField;
        }
        set {
            this.symbolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(1D)]
    public double Meritko {
        get {
            return this.meritkoField;
        }
        set {
            this.meritkoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double Odsazeni {
        get {
            return this.odsazeniField;
        }
        set {
            this.odsazeniField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TJednotkaSI : TJednotka {
    
    private TNazevJednotkySI nazevField;
    
    private TPredponaSI predponaField;
    
    private bool predponaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TNazevJednotkySI Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TPredponaSI Predpona {
        get {
            return this.predponaField;
        }
        set {
            this.predponaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PredponaSpecified {
        get {
            return this.predponaFieldSpecified;
        }
        set {
            this.predponaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TNazevJednotkySI {
    
    /// <remarks/>
    METRE,
    
    /// <remarks/>
    GRAM,
    
    /// <remarks/>
    SECOND,
    
    /// <remarks/>
    AMPERE,
    
    /// <remarks/>
    KELVIN,
    
    /// <remarks/>
    MOLE,
    
    /// <remarks/>
    CANDELA,
    
    /// <remarks/>
    RADIAN,
    
    /// <remarks/>
    STERADIAN,
    
    /// <remarks/>
    HERTZ,
    
    /// <remarks/>
    NEWTON,
    
    /// <remarks/>
    PASCAL,
    
    /// <remarks/>
    JOULE,
    
    /// <remarks/>
    WATT,
    
    /// <remarks/>
    COULOMB,
    
    /// <remarks/>
    VOLT,
    
    /// <remarks/>
    FARAD,
    
    /// <remarks/>
    OHM,
    
    /// <remarks/>
    SIEMENS,
    
    /// <remarks/>
    WEBER,
    
    /// <remarks/>
    TESLA,
    
    /// <remarks/>
    HENRY,
    
    /// <remarks/>
    DEGREE_CELSIUS,
    
    /// <remarks/>
    LUMEN,
    
    /// <remarks/>
    LUX,
    
    /// <remarks/>
    BECQUEREL,
    
    /// <remarks/>
    GRAY,
    
    /// <remarks/>
    SIEVERT,
    
    /// <remarks/>
    KATAL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TPredponaSI {
    
    /// <remarks/>
    YOTTA,
    
    /// <remarks/>
    ZETTA,
    
    /// <remarks/>
    EXA,
    
    /// <remarks/>
    PETA,
    
    /// <remarks/>
    TERA,
    
    /// <remarks/>
    GIGA,
    
    /// <remarks/>
    MEGA,
    
    /// <remarks/>
    KILO,
    
    /// <remarks/>
    HECTO,
    
    /// <remarks/>
    DECA,
    
    /// <remarks/>
    DECI,
    
    /// <remarks/>
    CENTI,
    
    /// <remarks/>
    MILLI,
    
    /// <remarks/>
    MICRO,
    
    /// <remarks/>
    NANO,
    
    /// <remarks/>
    PICO,
    
    /// <remarks/>
    FEMTO,
    
    /// <remarks/>
    ATTO,
    
    /// <remarks/>
    ZEPTO,
    
    /// <remarks/>
    YOCTO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TOdvozenaJednotka : TJednotka {
    
    private TKomponentaJednotky[] komponentaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Komponenta")]
    public TKomponentaJednotky[] Komponenta {
        get {
            return this.komponentaField;
        }
        set {
            this.komponentaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TCenovaSoustava {
    
    private string idField;
    
    private string nazevField;
    
    private string popisField;
    
    private string zdrojField;
    
    private string umisteniField;
    
    private string ediceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Zdroj {
        get {
            return this.zdrojField;
        }
        set {
            this.zdrojField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Umisteni {
        get {
            return this.umisteniField;
        }
        set {
            this.umisteniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Edice {
        get {
            return this.ediceField;
        }
        set {
            this.ediceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TTrida {
    
    private TTrida[] tridaField;
    
    private string idField;
    
    private string kodField;
    
    private string nazevField;
    
    private string popisField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trida")]
    public TTrida[] Trida {
        get {
            return this.tridaField;
        }
        set {
            this.tridaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TKlasifikace {
    
    private TTrida[] tridaField;
    
    private TTypKlasifikace typField;
    
    private string nazevField;
    
    private string popisField;
    
    private string zdrojField;
    
    private string umisteniField;
    
    private string ediceField;
    
    public TKlasifikace() {
        this.typField = TTypKlasifikace.Vlastni;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trida")]
    public TTrida[] Trida {
        get {
            return this.tridaField;
        }
        set {
            this.tridaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(TTypKlasifikace.Vlastni)]
    public TTypKlasifikace Typ {
        get {
            return this.typField;
        }
        set {
            this.typField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Zdroj {
        get {
            return this.zdrojField;
        }
        set {
            this.zdrojField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Umisteni {
        get {
            return this.umisteniField;
        }
        set {
            this.umisteniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Edice {
        get {
            return this.ediceField;
        }
        set {
            this.ediceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TTypKlasifikace {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CC-CZ")]
    CCCZ,
    
    /// <remarks/>
    CPV,
    
    /// <remarks/>
    CPA,
    
    /// <remarks/>
    CCI,
    
    /// <remarks/>
    Vlastni,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TOsoba {
    
    private TAdresa adresaField;
    
    private string jmenoField;
    
    private string telefonField;
    
    private string emailField;
    
    /// <remarks/>
    public TAdresa Adresa {
        get {
            return this.adresaField;
        }
        set {
            this.adresaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Jmeno {
        get {
            return this.jmenoField;
        }
        set {
            this.jmenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Telefon {
        get {
            return this.telefonField;
        }
        set {
            this.telefonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TOrganizace {
    
    private TAdresa adresaField;
    
    private TOsoba kontaktField;
    
    private string idField;
    
    private string nazevField;
    
    private string iCOField;
    
    private string dICField;
    
    private string telefonField;
    
    private string emailField;
    
    /// <remarks/>
    public TAdresa Adresa {
        get {
            return this.adresaField;
        }
        set {
            this.adresaField = value;
        }
    }
    
    /// <remarks/>
    public TOsoba Kontakt {
        get {
            return this.kontaktField;
        }
        set {
            this.kontaktField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ICO {
        get {
            return this.iCOField;
        }
        set {
            this.iCOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DIC {
        get {
            return this.dICField;
        }
        set {
            this.dICField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Telefon {
        get {
            return this.telefonField;
        }
        set {
            this.telefonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TDefinice {
    
    private TOrganizace[] organizaceField;
    
    private TKlasifikace[] klasifikaceField;
    
    private TCenovaSoustava[] cenovaSoustavaField;
    
    private TJednotka[] jednotkaField;
    
    private TSazbaDPH[] sazbaDPHField;
    
    private TMetodikaMereni[] metodikaMereniField;
    
    private int zaokrouhleniMnozstviPolozkyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Organizace")]
    public TOrganizace[] Organizace {
        get {
            return this.organizaceField;
        }
        set {
            this.organizaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Klasifikace")]
    public TKlasifikace[] Klasifikace {
        get {
            return this.klasifikaceField;
        }
        set {
            this.klasifikaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CenovaSoustava")]
    public TCenovaSoustava[] CenovaSoustava {
        get {
            return this.cenovaSoustavaField;
        }
        set {
            this.cenovaSoustavaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Jednotka")]
    public TJednotka[] Jednotka {
        get {
            return this.jednotkaField;
        }
        set {
            this.jednotkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SazbaDPH")]
    public TSazbaDPH[] SazbaDPH {
        get {
            return this.sazbaDPHField;
        }
        set {
            this.sazbaDPHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MetodikaMereni")]
    public TMetodikaMereni[] MetodikaMereni {
        get {
            return this.metodikaMereniField;
        }
        set {
            this.metodikaMereniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ZaokrouhleniMnozstviPolozky {
        get {
            return this.zaokrouhleniMnozstviPolozkyField;
        }
        set {
            this.zaokrouhleniMnozstviPolozkyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TPozadovanaVlastnost {
    
    private string popisField;
    
    private TJednotkaRef jednotkaField;
    
    private string idField;
    
    private string skupinaVlastnostiField;
    
    private string nazevField;
    
    private TTypHodnoty typHodnotyField;
    
    private string identifikatorDSSField;
    
    /// <remarks/>
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    public TJednotkaRef Jednotka {
        get {
            return this.jednotkaField;
        }
        set {
            this.jednotkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SkupinaVlastnosti {
        get {
            return this.skupinaVlastnostiField;
        }
        set {
            this.skupinaVlastnostiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TTypHodnoty TypHodnoty {
        get {
            return this.typHodnotyField;
        }
        set {
            this.typHodnotyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IdentifikatorDSS {
        get {
            return this.identifikatorDSSField;
        }
        set {
            this.identifikatorDSSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TTypHodnoty {
    
    /// <remarks/>
    TEXT,
    
    /// <remarks/>
    DECIMAL,
    
    /// <remarks/>
    REAL,
    
    /// <remarks/>
    INTEGER,
    
    /// <remarks/>
    BOOLEAL,
    
    /// <remarks/>
    DATUM_CAS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TOrganizaceRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TSazbaDPHRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TJednotkovaCena {
    
    private string komentarField;
    
    private decimal cenaField;
    
    /// <remarks/>
    public string Komentar {
        get {
            return this.komentarField;
        }
        set {
            this.komentarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Cena {
        get {
            return this.cenaField;
        }
        set {
            this.cenaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TMetodikaMereniRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TMnozstvi {
    
    private string vykazVymerField;
    
    private TJednotkaRef jednotkaField;
    
    private TMetodikaMereniRef skupinaMereniField;
    
    private decimal mnozstviField;
    
    /// <remarks/>
    public string VykazVymer {
        get {
            return this.vykazVymerField;
        }
        set {
            this.vykazVymerField = value;
        }
    }
    
    /// <remarks/>
    public TJednotkaRef Jednotka {
        get {
            return this.jednotkaField;
        }
        set {
            this.jednotkaField = value;
        }
    }
    
    /// <remarks/>
    public TMetodikaMereniRef SkupinaMereni {
        get {
            return this.skupinaMereniField;
        }
        set {
            this.skupinaMereniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Mnozstvi {
        get {
            return this.mnozstviField;
        }
        set {
            this.mnozstviField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TCenovaSoustavaRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TPolozkaRozpoctu {
    
    private string popisField;
    
    private TExterniEntita[] externiEntitaField;
    
    private TSkupinaVlastnosti[] skupinaVlastnostiField;
    
    private TTridaRef[] zatrideniField;
    
    private TCenovaSoustavaRef cenovaSoustavaField;
    
    private TMnozstvi mnozstviField;
    
    private string komentarField;
    
    private TJednotkovaCena jednotkovaCenaField;
    
    private TSazbaDPHRef sazbaDPHField;
    
    private string idField;
    
    private string nazevField;
    
    private string kodField;
    
    private string poradoveCisloField;
    
    private TTypPolozky typField;
    
    private bool typFieldSpecified;
    
    private double jednotkovaHmotnostField;
    
    private bool jednotkovaHmotnostFieldSpecified;
    
    private double jednotkovaDemontazniHmotnostField;
    
    private bool jednotkovaDemontazniHmotnostFieldSpecified;
    
    private bool prenesenaDPHField;
    
    private bool prenesenaDPHFieldSpecified;
    
    private string variantaField;
    
    private string zpusobilostField;
    
    /// <remarks/>
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExterniEntita")]
    public TExterniEntita[] ExterniEntita {
        get {
            return this.externiEntitaField;
        }
        set {
            this.externiEntitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SkupinaVlastnosti")]
    public TSkupinaVlastnosti[] SkupinaVlastnosti {
        get {
            return this.skupinaVlastnostiField;
        }
        set {
            this.skupinaVlastnostiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Zatrideni")]
    public TTridaRef[] Zatrideni {
        get {
            return this.zatrideniField;
        }
        set {
            this.zatrideniField = value;
        }
    }
    
    /// <remarks/>
    public TCenovaSoustavaRef CenovaSoustava {
        get {
            return this.cenovaSoustavaField;
        }
        set {
            this.cenovaSoustavaField = value;
        }
    }
    
    /// <remarks/>
    public TMnozstvi Mnozstvi {
        get {
            return this.mnozstviField;
        }
        set {
            this.mnozstviField = value;
        }
    }
    
    /// <remarks/>
    public string Komentar {
        get {
            return this.komentarField;
        }
        set {
            this.komentarField = value;
        }
    }
    
    /// <remarks/>
    public TJednotkovaCena JednotkovaCena {
        get {
            return this.jednotkovaCenaField;
        }
        set {
            this.jednotkovaCenaField = value;
        }
    }
    
    /// <remarks/>
    public TSazbaDPHRef SazbaDPH {
        get {
            return this.sazbaDPHField;
        }
        set {
            this.sazbaDPHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string PoradoveCislo {
        get {
            return this.poradoveCisloField;
        }
        set {
            this.poradoveCisloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TTypPolozky Typ {
        get {
            return this.typField;
        }
        set {
            this.typField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypSpecified {
        get {
            return this.typFieldSpecified;
        }
        set {
            this.typFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double JednotkovaHmotnost {
        get {
            return this.jednotkovaHmotnostField;
        }
        set {
            this.jednotkovaHmotnostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool JednotkovaHmotnostSpecified {
        get {
            return this.jednotkovaHmotnostFieldSpecified;
        }
        set {
            this.jednotkovaHmotnostFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double JednotkovaDemontazniHmotnost {
        get {
            return this.jednotkovaDemontazniHmotnostField;
        }
        set {
            this.jednotkovaDemontazniHmotnostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool JednotkovaDemontazniHmotnostSpecified {
        get {
            return this.jednotkovaDemontazniHmotnostFieldSpecified;
        }
        set {
            this.jednotkovaDemontazniHmotnostFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool PrenesenaDPH {
        get {
            return this.prenesenaDPHField;
        }
        set {
            this.prenesenaDPHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrenesenaDPHSpecified {
        get {
            return this.prenesenaDPHFieldSpecified;
        }
        set {
            this.prenesenaDPHFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Varianta {
        get {
            return this.variantaField;
        }
        set {
            this.variantaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Zpusobilost {
        get {
            return this.zpusobilostField;
        }
        set {
            this.zpusobilostField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TExterniEntita {
    
    private string idField;
    
    private string nazevField;
    
    private string zdrojField;
    
    private string umisteniField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Zdroj {
        get {
            return this.zdrojField;
        }
        set {
            this.zdrojField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Umisteni {
        get {
            return this.umisteniField;
        }
        set {
            this.umisteniField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TSkupinaVlastnosti {
    
    private string popisField;
    
    private TVlastnost[] vlastnostField;
    
    private string nazevField;
    
    /// <remarks/>
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Vlastnost")]
    public TVlastnost[] Vlastnost {
        get {
            return this.vlastnostField;
        }
        set {
            this.vlastnostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TVlastnostDatum))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TVlastnostBoolean))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TVlastnostIntegral))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TVlastnostReal))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TVlastnostDecimal))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TVlastnostText))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public abstract partial class TVlastnost {
    
    private string popisField;
    
    private TJednotkaRef jednotkaField;
    
    private TPozadovanaVlastnostRef pozadavekField;
    
    private string nazevField;
    
    private string identifikatorDSSField;
    
    private bool ovlivnujeCenuField;
    
    /// <remarks/>
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    public TJednotkaRef Jednotka {
        get {
            return this.jednotkaField;
        }
        set {
            this.jednotkaField = value;
        }
    }
    
    /// <remarks/>
    public TPozadovanaVlastnostRef Pozadavek {
        get {
            return this.pozadavekField;
        }
        set {
            this.pozadavekField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IdentifikatorDSS {
        get {
            return this.identifikatorDSSField;
        }
        set {
            this.identifikatorDSSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool OvlivnujeCenu {
        get {
            return this.ovlivnujeCenuField;
        }
        set {
            this.ovlivnujeCenuField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TPozadovanaVlastnostRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TVlastnostDatum : TVlastnost {
    
    private System.DateTime hodnotaField;
    
    private bool hodnotaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Hodnota {
        get {
            return this.hodnotaField;
        }
        set {
            this.hodnotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HodnotaSpecified {
        get {
            return this.hodnotaFieldSpecified;
        }
        set {
            this.hodnotaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TVlastnostBoolean : TVlastnost {
    
    private bool hodnotaField;
    
    private bool hodnotaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Hodnota {
        get {
            return this.hodnotaField;
        }
        set {
            this.hodnotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HodnotaSpecified {
        get {
            return this.hodnotaFieldSpecified;
        }
        set {
            this.hodnotaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TVlastnostIntegral : TVlastnost {
    
    private long hodnotaField;
    
    private bool hodnotaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Hodnota {
        get {
            return this.hodnotaField;
        }
        set {
            this.hodnotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HodnotaSpecified {
        get {
            return this.hodnotaFieldSpecified;
        }
        set {
            this.hodnotaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TVlastnostReal : TVlastnost {
    
    private double hodnotaField;
    
    private bool hodnotaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Hodnota {
        get {
            return this.hodnotaField;
        }
        set {
            this.hodnotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HodnotaSpecified {
        get {
            return this.hodnotaFieldSpecified;
        }
        set {
            this.hodnotaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TVlastnostDecimal : TVlastnost {
    
    private decimal hodnotaField;
    
    private bool hodnotaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Hodnota {
        get {
            return this.hodnotaField;
        }
        set {
            this.hodnotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HodnotaSpecified {
        get {
            return this.hodnotaFieldSpecified;
        }
        set {
            this.hodnotaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TVlastnostText : TVlastnost {
    
    private string hodnotaField;
    
    /// <remarks/>
    public string Hodnota {
        get {
            return this.hodnotaField;
        }
        set {
            this.hodnotaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TTridaRef {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TTypPolozky {
    
    /// <remarks/>
    HSV,
    
    /// <remarks/>
    PSV,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    OSTATNI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TPoloha {
    
    private double zemSirkaField;
    
    private double zemDelkaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double ZemSirka {
        get {
            return this.zemSirkaField;
        }
        set {
            this.zemSirkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double ZemDelka {
        get {
            return this.zemDelkaField;
        }
        set {
            this.zemDelkaField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TUzelRozpoctu))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TObjekt))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TRozpocet))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TProjekt))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public abstract partial class TIdentita {
    
    private string popisField;
    
    private TExterniEntita[] externiEntitaField;
    
    private TSkupinaVlastnosti[] skupinaVlastnostiField;
    
    private string idField;
    
    private string nazevField;
    
    /// <remarks/>
    public string Popis {
        get {
            return this.popisField;
        }
        set {
            this.popisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExterniEntita")]
    public TExterniEntita[] ExterniEntita {
        get {
            return this.externiEntitaField;
        }
        set {
            this.externiEntitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SkupinaVlastnosti")]
    public TSkupinaVlastnosti[] SkupinaVlastnosti {
        get {
            return this.skupinaVlastnostiField;
        }
        set {
            this.skupinaVlastnostiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TUzelRozpoctu : TIdentita {
    
    private TTridaRef[] zatrideniField;
    
    private TUzelRozpoctu[] uzelRozpoctuField;
    
    private TPolozkaRozpoctu[] polozkaField;
    
    private TTypUzlu typField;
    
    private string vlastniTypField;
    
    private string kodField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Zatrideni")]
    public TTridaRef[] Zatrideni {
        get {
            return this.zatrideniField;
        }
        set {
            this.zatrideniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UzelRozpoctu")]
    public TUzelRozpoctu[] UzelRozpoctu {
        get {
            return this.uzelRozpoctuField;
        }
        set {
            this.uzelRozpoctuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Polozka")]
    public TPolozkaRozpoctu[] Polozka {
        get {
            return this.polozkaField;
        }
        set {
            this.polozkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TTypUzlu Typ {
        get {
            return this.typField;
        }
        set {
            this.typField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VlastniTyp {
        get {
            return this.vlastniTypField;
        }
        set {
            this.vlastniTypField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TTypUzlu {
    
    /// <remarks/>
    DIL,
    
    /// <remarks/>
    VLASTNI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TObjekt : TIdentita {
    
    private TTridaRef[] zatrideniField;
    
    private TUzelRozpoctu[] uzelRozpoctuField;
    
    private TPolozkaRozpoctu[] polozkaField;
    
    private string kSOField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Zatrideni")]
    public TTridaRef[] Zatrideni {
        get {
            return this.zatrideniField;
        }
        set {
            this.zatrideniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UzelRozpoctu")]
    public TUzelRozpoctu[] UzelRozpoctu {
        get {
            return this.uzelRozpoctuField;
        }
        set {
            this.uzelRozpoctuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Polozka")]
    public TPolozkaRozpoctu[] Polozka {
        get {
            return this.polozkaField;
        }
        set {
            this.polozkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string KSO {
        get {
            return this.kSOField;
        }
        set {
            this.kSOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public partial class TRozpocet : TIdentita {
    
    private TObjekt[] objektField;
    
    private TOrganizaceRef objednatelField;
    
    private TOrganizaceRef uchazecField;
    
    private TPozadovanaVlastnost[] informacniPozadavkyField;
    
    private System.DateTime datumVytvoreniRozpoctuField;
    
    private System.DateTime datumOceneniField;
    
    private bool povinnaSkupinaMereniField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Objekt")]
    public TObjekt[] Objekt {
        get {
            return this.objektField;
        }
        set {
            this.objektField = value;
        }
    }
    
    /// <remarks/>
    public TOrganizaceRef Objednatel {
        get {
            return this.objednatelField;
        }
        set {
            this.objednatelField = value;
        }
    }
    
    /// <remarks/>
    public TOrganizaceRef Uchazec {
        get {
            return this.uchazecField;
        }
        set {
            this.uchazecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Pozadavek", IsNullable=false)]
    public TPozadovanaVlastnost[] InformacniPozadavky {
        get {
            return this.informacniPozadavkyField;
        }
        set {
            this.informacniPozadavkyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime DatumVytvoreniRozpoctu {
        get {
            return this.datumVytvoreniRozpoctuField;
        }
        set {
            this.datumVytvoreniRozpoctuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime DatumOceneni {
        get {
            return this.datumOceneniField;
        }
        set {
            this.datumOceneniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool PovinnaSkupinaMereni {
        get {
            return this.povinnaSkupinaMereniField;
        }
        set {
            this.povinnaSkupinaMereniField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.koncepcebim.cz/ORF_v0.1.xsd")]
public enum TVerze {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("v1.0")]
    v10,
}
