// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.0.0. www.xsd2code.com
//    {"TargetFramework":"NetStandard","NameSpace":"ORF.XML","GenerateUnusedComplexType":true,"GenerateUnusedSimpleType":true,"Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ORF.XML
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;
    
    
    [XmlIncludeAttribute(typeof(TMonetaryUnit))]
    [XmlIncludeAttribute(typeof(TContextDependentUnit))]
    [XmlIncludeAttribute(typeof(TConversionUnit))]
    [XmlIncludeAttribute(typeof(TDerivedUnit))]
    [XmlIncludeAttribute(typeof(TSIUnit))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://tempuri.org/Units.xsd")]
    [XmlRootAttribute(Namespace="http://tempuri.org/Units.xsd", IsNullable=true)]
    public abstract partial class TUnit
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://tempuri.org/Units.xsd")]
    public partial class TMonetaryUnit : TUnit
    {
        #region Private fields
        private string _currency;
        #endregion
        
        [XmlAttribute]
        public string Currency
        {
            get
            {
                return _currency;
            }
            set
            {
                _currency = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://tempuri.org/Units.xsd")]
    public partial class TContextDependentUnit : TUnit
    {
        #region Private fields
        private string _name;
        private string _symbol;
        #endregion
        
        [XmlAttribute]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
        
        [XmlAttribute]
        public string Symbol
        {
            get
            {
                return _symbol;
            }
            set
            {
                _symbol = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://tempuri.org/Units.xsd")]
    public partial class TConversionUnit : TUnit
    {
        #region Private fields
        private TUnit _baseUnit;
        private string _name;
        private string _symbol;
        private double _scale;
        private double _offset;
        #endregion
        
        public TConversionUnit()
        {
            _scale = 1D;
            _offset = 0D;
        }
        
        public TUnit BaseUnit
        {
            get
            {
                return _baseUnit;
            }
            set
            {
                _baseUnit = value;
            }
        }
        
        [XmlAttribute]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
        
        [XmlAttribute]
        public string Symbol
        {
            get
            {
                return _symbol;
            }
            set
            {
                _symbol = value;
            }
        }
        
        [XmlAttribute]
        [DefaultValue(1D)]
        public double Scale
        {
            get
            {
                return _scale;
            }
            set
            {
                _scale = value;
            }
        }
        
        [XmlAttribute]
        [DefaultValue(0D)]
        public double Offset
        {
            get
            {
                return _offset;
            }
            set
            {
                _offset = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://tempuri.org/Units.xsd")]
    public partial class TDerivedUnit : TUnit
    {
        #region Private fields
        private List<TDerivedUnitComponent> _component;
        #endregion
        
        public TDerivedUnit()
        {
            _component = new List<TDerivedUnitComponent>();
        }
        
        [XmlElement("Component")]
        public List<TDerivedUnitComponent> Component
        {
            get
            {
                return _component;
            }
            set
            {
                _component = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Units.xsd")]
    public partial class TDerivedUnitComponent
    {
        #region Private fields
        private TSIUnit _unit;
        private string _exponent;
        #endregion
        
        public TDerivedUnitComponent()
        {
            _unit = new TSIUnit();
        }
        
        public TSIUnit Unit
        {
            get
            {
                return _unit;
            }
            set
            {
                _unit = value;
            }
        }
        
        [XmlAttribute(DataType="integer")]
        public string Exponent
        {
            get
            {
                return _exponent;
            }
            set
            {
                _exponent = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://tempuri.org/Units.xsd")]
    public partial class TSIUnit : TUnit
    {
        #region Private fields
        private SIUnitName _name;
        private SIUnitPrefix _prefix;
        #endregion
        
        [XmlAttribute]
        public SIUnitName Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
        
        [XmlAttribute]
        public SIUnitPrefix Prefix
        {
            get
            {
                return _prefix;
            }
            set
            {
                _prefix = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace="http://tempuri.org/Units.xsd")]
    public enum SIUnitName
    {
        metre,
        kilogram,
        second,
        ampere,
        kelvin,
        mole,
        candela,
        radian,
        steradian,
        hertz,
        newton,
        pascal,
        joule,
        watt,
        coulomb,
        volt,
        farad,
        ohm,
        siemens,
        weber,
        tesla,
        henry,
        degree_Celsius,
        lumen,
        lux,
        becquerel,
        gray,
        sievert,
        katal,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace="http://tempuri.org/Units.xsd")]
    public enum SIUnitPrefix
    {
        yotta,
        zetta,
        exa,
        peta,
        tera,
        giga,
        mega,
        kilo,
        hecto,
        deca,
        deci,
        centi,
        milli,
        micro,
        nano,
        pico,
        femto,
        atto,
        zepto,
        yocto,
    }
}
#pragma warning restore
